import { Command } from 'commander';
import { join } from 'node:path';
import { detectProject, getProjectInfo } from '../../core/project.js';
import { scanProject } from '../../core/scanner.js';
import { readFileSafe, writeFileSafe } from '../../utils/fs.js';
import { error, success, indent, header } from '../../utils/logger.js';
import { confirm } from '../../utils/prompt.js';

export const docsCommand = new Command('docs')
  .description('Generate documentation for environment variables')
  .option('--output <path>', 'Output file', 'ENV.md')
  .option('--overwrite', 'Overwrite existing file without prompting')
  .action(async (options: { output: string; overwrite?: boolean }) => {
    const cwd = process.cwd();
    const projectPath = await detectProject(cwd);

    if (!projectPath) {
      console.log(error('No package.json found. Are you in a project directory?'));
      process.exit(1);
    }

    await runDocs(projectPath, options.output, options.overwrite ?? false);
  });

export async function runDocs(
  projectPath: string,
  outputFile: string,
  overwrite: boolean
): Promise<void> {
  const info = await getProjectInfo(projectPath);
  const references = await scanProject(projectPath);
  const referencedKeys = new Set(references.map((r) => r.key));
  const definedKeys = new Set(info.envFiles.flatMap((f) => f.variables.map((v) => v.key)));

  const outputPath = join(projectPath, outputFile);
  const existing = await readFileSafe(outputPath);

  if (existing && !overwrite) {
    const confirmed = await confirm(`${outputFile} already exists. Overwrite?`);
    if (!confirmed) {
      console.log(indent('Aborted. No changes made.'));
      return;
    }
  }

  const missingKeys = new Set(
    info.issues
      .filter((i) => i.type === 'missing')
      .map((i) => i.key)
  );

  const lines: string[] = [];
  lines.push(`# Environment Variables — ${info.name}`);
  lines.push('');
  lines.push(`Generated by [enve](https://enve-lac.vercel.app) on ${new Date().toISOString().slice(0, 10)}.`);
  lines.push('');
  lines.push(`**Health score:** ${info.score.score}/100 (${info.score.grade})`);
  lines.push('');

  if (info.issues.length > 0) {
    lines.push('## Issues');
    lines.push('');
    for (const issue of info.issues) {
      const badge = issue.severity === 'error' ? '🔴' : issue.severity === 'warning' ? '🟡' : '🔵';
      lines.push(`- ${badge} **${issue.key}** — ${issue.message}`);
      if (issue.suggestion) {
        lines.push(`  → ${issue.suggestion}`);
      }
    }
    lines.push('');
  }

  lines.push('## Variables');
  lines.push('');
  lines.push('| Variable | Source | Used in code | Secret | Notes |');
  lines.push('| --- | --- | --- | --- | --- |');

  for (const file of info.envFiles) {
    for (const variable of file.variables) {
      const isUsed = referencedKeys.has(variable.key);
      const notes: string[] = [];
      if (variable.comment) notes.push(variable.comment);
      if (variable.isSecret) notes.push('treat as secret');

      lines.push(
        `| \`${variable.key}\` | ${file.filename} | ${isUsed ? 'Yes' : 'No'} | ${variable.isSecret ? 'Yes' : 'No'} | ${notes.join(', ') || '-'} |`
      );
    }
  }

  if (missingKeys.size > 0) {
    for (const key of missingKeys) {
      if (definedKeys.has(key)) continue;
      lines.push(`| \`${key}\` | — | No (missing) | No | Referenced in code but not defined |`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('Keep this file up to date by running `enve docs`.');
  lines.push('');

  await writeFileSafe(outputPath, lines.join('\n'));

  console.log();
  console.log(indent(header(`Generated ${outputFile}`)));
  console.log();
  console.log(indent(success(`Wrote ${lines.length} lines to ${outputPath}`)));
}
